version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: ludo-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ludo_multiplayer
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ludo-network

  backend:
    build: ./backend
    container_name: ludo-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/ludo_multiplayer?authSource=admin
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - SESSION_SECRET=ludo-secret-key-for-docker
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - ludo-network

  frontend:
    build: ./frontend
    container_name: ludo-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ludo-network

volumes:
  mongodb_data:

networks:
  ludo-network:
    driver: bridge
